def opening_sequence():
    input("(press enter to continue)")
    print("\n" * 100)
    input("it's a dark and rainy night\n")
    print("\n" * 100)
    input("You have been here before. You don't remember when or why, but you know that you have been here before.\n")
    print("\n" * 100)
    input("You don't even know why you're here now for that matter.\n")
    print("\n" * 100)
    input("You just know there is some force that has been pushing you here for some time.\n")
    print("\n" * 100)
    input("As you look upon the black walls of the castle in the distance, you feel the presence of a million fleeting memories\n")
    print("\n" * 100)
    input("Regardless you press on, throwing caution to the wind.\n")
    print("\n" * 100)
    input("As you keep walking, you grow ever closer to the castle\n")
    print("\n" * 100)
    input("You finally arrive at the castle doors. How do you want to open them\n")
    print("(input how you want to open the doors)\n")
    door_open = input()
    print("You", door_open, "the doors exposing the castle interior\n")
    print("\n" * 100)
    input("You take one last look around at the open sky before you head into the castle")
    print("\n" * 100)
    input("As you walk in you hear the doors close behind you, sealing shut.")
    return


opening_sequence()